'use client'
import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabaseClient'
export default function AdminTasks(){
  const [list,setList]=useState([]); const [title,setTitle]=useState(''); const [desc,setDesc]=useState(''); const [priority,setPriority]=useState('medium'); const [assignees,setAssignees]=useState([]); const [users,setUsers]=useState([])
  async function load(){ const { data:tasks } = await supabase.from('tasks').select('*').order('created_at',{ascending:false}); setList(tasks||[]); const { data:prof } = await supabase.from('profiles').select('id,name,email').neq('role','pending'); setUsers(prof||[]) }
  useEffect(()=>{ load() },[])
  async function createTask(){ const { data:t, error } = await supabase.from('tasks').insert({title,description:desc,priority}).select('*').single(); if(error) return alert(error.message); if(assignees.length){ await supabase.from('task_assignees').insert(assignees.map(u=>({task_id:t.id,user_id:u}))); await fetch('/api/notify/task-created',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({task_id:t.id})}) } setTitle(''); setDesc(''); setAssignees([]); load() }
  return (<div className="space-y-4"><div className="card space-y-2"><h1 className="text-xl font-bold">Tasks (Admin)</h1><input className="input" placeholder="Title" value={title} onChange={e=>setTitle(e.target.value)}/><textarea className="input" placeholder="Description" value={desc} onChange={e=>setDesc(e.target.value)}/><div className="grid grid-cols-1 sm:grid-cols-3 gap-2"><select className="input" value={priority} onChange={e=>setPriority(e.target.value)}><option>low</option><option>medium</option><option>high</option></select><select multiple className="input" value={assignees} onChange={e=>setAssignees(Array.from(e.target.selectedOptions).map(o=>o.value))}>{users.map(u=>(<option key={u.id} value={u.id}>{u.name||u.email}</option>))}</select><button className="btn btn-primary" onClick={createTask}>Create & Assign</button></div></div><div className="space-y-2">{list.map(t=>(<div key={t.id} className="card"><div className="flex items-center justify-between"><div className="font-semibold">{t.title}</div><span className="badge">{t.priority}</span></div><div className="text-sm text-gray-600">{t.description||''}</div></div>))}</div></div>)}
