'use client'
import { useEffect, useState } from 'react'
import { makeIdemKey } from '@/lib/idempotency'
import { haversineMeters, softGate } from '@/lib/geo'
import { enqueue, flushNow, listenForSWFlush } from '@/lib/offlineQueue'
export default function Home(){
  const [loading,setLoading]=useState(false); const [note,setNote]=useState(''); const [coords,setCoords]=useState(null); const [store,setStore]=useState(null)
  useEffect(()=>{ if(navigator.geolocation){ navigator.geolocation.getCurrentPosition(p=>setCoords({lat:p.coords.latitude,lon:p.coords.longitude}),()=>setCoords(null),{enableHighAccuracy:true,timeout:6000}) } listenForSWFlush() },[])
  async function act(kind){ setLoading(true); try{ const idem=makeIdemKey(kind[0]); let geoFlag=null; if(coords && store && typeof store.lat==='number'){ const d=haversineMeters(coords,{lat:store.lat,lon:store.lon}); const ok=softGate(d,store.radius_m||150,store.grace_m||0); if(!ok){ const c=confirm(`You appear to be ~${Math.round(d)}m from store. Proceed?`); if(!c){ setLoading(false); return } geoFlag=`geo_outside_${Math.round(d)}m` } } const body={kind,note,coords,idem,geoFlag}; const res=await fetch('/api/punch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); if(res.ok){ alert(`${kind.replace('_',' ').toUpperCase()} recorded`+(geoFlag?` · ${geoFlag}`:'')); setNote(''); return } await enqueue({...body}); alert('No network. Saved offline; will auto‑flush when online.') }catch(e){ await enqueue({kind,note,coords,idem:makeIdemKey('op')}); alert('Saved offline; will auto‑flush when online.') } finally{ setLoading(false); flushNow() } }
  return (<div className="grid grid-cols-1 md:grid-cols-3 gap-[var(--gap)]"><div className="card space-y-3 md:col-span-2"><h2 className="text-lg font-semibold">Quick Actions</h2><textarea className="input" placeholder="Reason / note (optional)" value={note} onChange={e=>setNote(e.target.value)}/><div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><button disabled={loading} className="btn btn-primary" onClick={()=>act('in')}>Punch In</button><button disabled={loading} className="btn btn-outline" onClick={()=>act('out')}>Punch Out</button><button disabled={loading} className="btn btn-primary" onClick={()=>act('break_out')}>Break Out</button><button disabled={loading} className="btn btn-outline" onClick={()=>act('break_in')}>Break In</button></div><div className="text-xs text-gray-500">GPS: {coords?`${coords.lat.toFixed(5)}, ${coords.lon.toFixed(5)}`:'n/a'}</div></div><div className="card space-y-2"><h2 className="text-lg font-semibold">Status</h2><div className="text-sm text-brand-muted">Auto‑out at 23:59 • Reminders on</div><div className="flex flex-wrap gap-2"><span className="badge">Geo‑fence</span><span className="badge">Offline Queue</span><span className="badge">Tasks</span></div></div></div>)}
